### PR TITLE
Update meta.yaml: add python

### PR DESCRIPTION
**Pull request by hainm**
I got FileNotFound error if not specifying python.

### CODE REVIEW

**Comment by jaimergp** [comment]
Actually, it should be python=2, right?

**Comment by hainm** [comment]
Might be. I switched to py2 env and that change worked for me. :d

**Comment by jaimergp** [comment]
Hi @hainm! Were you able to check if `python=2.7` was really needed?

**Comment by hainm** [comment]
Hi

I think chimera only works with py2.

Hai

**Comment by jaimergp** [comment]
Yes, but Chimera ships its own interpreter. This is just a recipe and theoretically it shouldn't need more build dependencies than those listed in the build scripts.

**Comment by jaimergp** [comment]
Closed by last commit. Thanks for the report!

**Comment by hainm** [comment]
yeah. If users like me use py3 to pull your built, this won't work with chimera py2. Specifying python version will prevent this from the beginning.

**Pull request closed without merging**
